Cloud Application/MediaLibrary/MediaLibrary/MediaLibrary/Controllers/MediaController.cs
using ControllerLayer;
using MediaLibrary.Models;
using ModelLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ControllerLayer.DTOCollection;

namespace MediaLibrary.Controllers
{
    public class MediaController : Controller
    {

        IMediaManager mediaManager = new MediaManagerImpl();
        IUserManager userManager = new UserManagerImpl();
        // GET: Media
        public ActionResult MediaDisplay()
        {
            if (Session["UserLevel"] != null)
            {
                ViewBag.media = mediaManager.ViewMedia();
                return View();
            }
            return View("~/Views/User/LoginUser.cshtml");
        }


        public ActionResult ViewDirectors()
        {
            ViewBag.directors = mediaManager.getDirectors();
            return View();
        }

        public ActionResult ViewLanguage()
        {
            ViewBag.language = mediaManager.getLanguage();
            return View();
        }

        public ActionResult ViewGenre()
        {
            ViewBag.genre = mediaManager.getGenre();
            return View();
        }

        public ActionResult InsertMedia(Media medias)
        {
            if ((int)Session["UserLevel"] == 3)
            {
                IMediaManager mediaManager = new MediaManagerImpl();

                int value = mediaManager.InsertMedia(medias.Title, medias.Genere, medias.Director, medias.Language, medias.PublishYear, medias.Budget);

                var viewDirectors = mediaManager.getDirectors();
                var viewGenre = mediaManager.getGenre();
                var viewLanguage = mediaManager.getLanguage();

                ViewBag.Director = viewDirectors;
                ViewBag.Genre = viewGenre;
                ViewBag.Language = viewLanguage;

                if (value > 0)
                {
                    MediaDisplay();
                    return View("MediaDisplay");
                }
            }
            return View();
        }

        public ActionResult DeleteMedia(Media model)
        {
            if ((int)Session["UserLevel"] == 3)
            {
                mediaManager.DeleteMedia(model.MediaID);
            }
            MediaDisplay();
            return View("MediaDisplay");
        }

        public ActionResult BrowseAll(Media booksModel)
        {
            var column = booksModel.selection;
            var value = booksModel.input;
            var listOfBooks = mediaManager.viewMediaByValue(value, column);
            ViewBag.media = listOfBooks;
            return View("MediaDisplay");
        }

        public ActionResult InputBorrow(UserValue userValue, Media media)
        {
            DateTime dateTime = DateTime.Now;
            string todayStr = dateTime.ToString();
            DateTime returnDate = dateTime.AddDays(10);
            string returnDateStr = returnDate.ToString();
            userManager.InsertBorrow(userValue.UID, media.MediaID, todayStr,returnDateStr);
            ViewBag.msg = "Borrowed";
            MediaDisplay();
            return View("MediaDisplay");
        }

        public ActionResult InsertReserve(UserValue userValue, Media media)
        {
            string date = DateTime.Now.ToString();
            userManager.InsertReserve(userValue.UID, media.MediaID, date);
            ViewBag.msg = "Media is Reserved. Enjoy!!!!";
            MediaDisplay();
            return View("MediaDisplay");
        }

        public ActionResult ReserveGet()
        {

            var reserveList = userManager.GetReserves();
            ViewBag.reserveList = reserveList;
            return View();
        }

        public ActionResult ShowBorrow()
        {
            var borrowList = userManager.GetBorrows((int)'1');
            ViewBag.borrowList = borrowList;
            return View();
        }

        public ActionResult InsertReturn(Models.Borrow borrowModel)
        {
            DateTime today = DateTime.Now;
            string todayStr = today.ToString();
            string returnDateStr = borrowModel.ReturnDate;
            DateTime returnDate = DateTime.Parse(returnDateStr);
            double diff = (today - returnDate).TotalDays;
            int difference = (int)diff;
            if (difference < 0)
            {
                difference = 0;
            }
            decimal lateFee = difference * 10;
            userManager.InsertReturn(todayStr, lateFee, borrowModel.BID, borrowModel.MediaID);

            ShowBorrow();
            return View("ShowBorrow");
        }

        public ActionResult UpdateMedia(Media media)
        {
            if ((int)Session["UserLevel"] == 3)
            {
                int row = mediaManager.UpdateMedia(media.Title, media.Genere, media.Director, media.Language, media.PublishYear, media.Budget, media.MediaID);
                IMediaManager mediaManagerImpl = new MediaManagerImpl();
                var allDirectors = mediaManagerImpl.getDirectors();
                var allGenre = mediaManagerImpl.getGenre();
                var allLang = mediaManagerImpl.getLanguage();

                ViewBag.Directors = allDirectors;
                ViewBag.Genre = allGenre;
                ViewBag.Languages = allLang;


                if (row > 0)
                {
                    MediaDisplay();
                    return View("MediaDisplay");
                }
            }
            return View();
        }

        public ActionResult InsertDirector(Directors dirDTO)
        {
            int row = mediaManager.InsertDirector(dirDTO.DirectorName);
            ViewDirectors();
            return View("ViewDirectors");
        }

        public ActionResult InsertLanguage(Language languageDTO)
        {
            int row = mediaManager.InsertLanguage(languageDTO.LanguageName);
            ViewLanguage();
            return View("ViewLanguage");
        }

        public ActionResult InsertGenre(Genre genreDTO)
        {
            int row = mediaManager.InsertGenre(genreDTO.GenreName);
            ViewGenre();
            return View("ViewGenre");
        }

        public ActionResult DeleteGenre(Genre genreDTO)
        {
            mediaManager.DeleteGenre(genreDTO.GID);
            ViewGenre();
            return View("ViewGenre");

        }
            public ActionResult DeleteDirector(Directors directorDTO)
            {
                mediaManager.DeleteDirector(directorDTO.DID);
            ViewDirectors();
                return View("ViewDirectors");
            }

            public ActionResult DeleteLanguage(Language languageDTO)
            {
                mediaManager.DeleteGenre(languageDTO.LID);
            ViewLanguage();
                return View("ViewLanguage");
            }

        public ActionResult UpdateGenre(Genre genDTO)
        {
            int row = mediaManager.UpdateGenre(genDTO.GenreName, genDTO.GID);
            ViewGenre();
            return View("ViewGenre");
        }

        public ActionResult UpdateLanguage(Language languageDTO)
        {
            int row = mediaManager.UpdateLanguage(languageDTO.LanguageName, languageDTO.LID);
            ViewLanguage();
            return View("ViewLanguage");
        }

        public ActionResult UpdateDirector(Directors directorDTO)
        {
            int row = mediaManager.UpdateDirector(directorDTO.DirectorName, directorDTO.DID);
            ViewDirectors();
            return View("ViewDirector");
        }
    }
}

Cloud Application/MediaLibrary/MediaLibrary/MediaLibrary/Controllers/UserController.cs
using ControllerLayer;
using MediaLibrary.Models;
using ModelLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Collections.Specialized.BitVector32;

namespace MediaLibrary.Controllers
{
    public class UserController : Controller
    {
        IUserManager userManager = new UserManagerImpl();
        // GET: User
        public ActionResult ShowUsers()
        {

            var users = userManager.getUsers();
            ViewBag.userManager = users;

            return View();
        }


        public ActionResult LoginUser()
        {
            return View();
        }

        public ActionResult UserVerify(UserValue userAccount)
        {
            IUserManager userManager = new UserManagerImpl();

            bool validUser = userManager.userVerify(userAccount.userName, userAccount.password);

            if (validUser )
            {
                Session["UserName"] = userAccount.userName;
                Session["UID"] = userAccount.UID;
                Session["UserLevel"] = userAccount.userLevel;
                ViewBag.user = userAccount.userName;

                return View("~/Views/Media/MediaDisplay.cshtml");

            }

            else
            {
                ViewBag.user = null;
                return View("LoginUser");
            }
        }
        public ActionResult InsertUser(UserValue userAccount)
        {
            if (userAccount.userName != null && userAccount.password != null)
            {
                userManager.InsertUser(userAccount.userName, userAccount.userEmail, userAccount.userLevel, userAccount.password);
                ShowUsers();
                return View("ShowUsers");
            }
            ViewBag.ValidateMsg = "Please Try Again !";
           
                return View();
            
        }

        public ActionResult DeleteUser(UserValue userAccount)
        {
            userManager.DeleteUser(userAccount.UID);
            ShowUsers();
            return View("ShowUsers");
        }


        public ActionResult Logout()
        {
            Session.Clear();
            return View("~/Views/Home/Index.cshtml");
        }


        public ActionResult UpdateUser(UserValue userModel)
        {
            if (userModel.userName != null)
            {
                userManager.UpdateUser(userModel.UID, userModel.userName, userModel.userEmail, userModel.userLevel, userModel.password);
                ShowUsers();
                return View("ShowUsers");
            }
            return View();

        }


    }
}

Cloud Application/MediaLibrary/MediaLibrary/MediaLibrary/Views/User/InsertUser.cshtml
@model MediaLibrary.Models.UserValue
@{
    ViewBag.Title = "InsertUser";
}

<h2>InsertUser</h2>
<div class="container">
    @using (Html.BeginForm("InsertUser", "User", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.userName)
            @Html.TextBoxFor(m => m.userName, new { @class = "form-control", @placeholder = "UserName" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.userEmail)
            @Html.TextBoxFor(m => m.userEmail, new { @class = "form-control", @placeholder = "Email" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.password)
            @Html.TextBoxFor(m => m.password, new { @class = "form-control", @placeholder = "Password", @type = "Password" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.userLevel)
            @Html.TextBoxFor(m => m.userLevel, new { @class = "form-control", @placeholder = "Access Level" })
        </div>
        <input type="submit" value="Add User" class="btn btn-primary" />

    }
</div>

Cloud Application/MediaLibrary/MediaLibrary/MediaLibrary/Views/User/LoginUser.cshtml
@model MediaLibrary.Models.UserValue

@{
    ViewBag.Title = "LoginUser";
}


<h2>LoginUser</h2>
<div class="container">
    @using (@Html.BeginForm("MediaDisplay", "Media", FormMethod.Post))
    {
        @Html.LabelFor(model => model.userName, "User Name")<br />
        @Html.TextBoxFor(model => model.userName)<br />
        @Html.LabelFor(model => model.password, "Password")<br />
        @Html.PasswordFor(model => model.password)<br />
        <input type="submit" class="btn btn-primary" />
    }
        <h3><small style="color:red;">@ViewBag.ValidateMsg</small></h3>
</div>


Cloud Application/MediaLibrary/MediaLibrary/MediaLibrary/Views/User/ShowUsers.cshtml
@model MediaLibrary.Models.UserValue

@{
    ViewBag.Title = "ShowUsers";
}

<h2>ShowUsers</h2>

@Html.ActionLink("Add New User", "InsertUser", "User", null, new { @class = "btn btn-primary", @style = "margin-bottom:15px;margin-right:15px;" })
@Html.ActionLink("Update User", "UpdateUser", "User", null, new { @class = "btn btn-primary", @style = "margin-bottom:15px;margin-right:15px;" })
<div class="table-responsive">
    <table class="table table-hover" style="border:double">
        <tr style="border:double">
            <th>User ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Access Level</th>
            <th style="text-align:center;">Delete</th>
        </tr>
        @foreach (var allUser in ViewBag.userManager)
        {
            <tr>
                <td>
                    @allUser.UID
                </td>
                <td>
                    @allUser.userName
                </td>
                <td>
                    @allUser.userEmail
                </td>
                <td>
                    @allUser.password
                </td>
                <td>
                    @allUser.userLevel
                </td>
                <td style="text-align:center;">
                    @Html.ActionLink("Delete", "DeleteUser", "User", new { UID = allUser.UID, UserValue = Model }, new { @class = "btn btn-primary" })
                </td>

            </tr>
        }
    </table>
</div>

Cloud Application/MediaLibrary/MediaLibrary/MediaLibrary/Views/User/UpdateUser.cshtml
@model MediaLibrary.Models.UserValue

@{
    ViewBag.Title = "UpdateUser";
}

<h2>UpdateUser</h2>

<div class="container">
    @using (Html.BeginForm("UpdateUser", "User", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.UID)
            @Html.TextBoxFor(m => m.UID, new { @class = "form-control", @placeholder = "User ID" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.userName)
            @Html.TextBoxFor(m => m.userName, new { @class = "form-control", @placeholder = "Name" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.userEmail)
            @Html.TextBoxFor(m => m.userEmail, new { @class = "form-control", @placeholder = "Email" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.password)
            @Html.TextBoxFor(m => m.password, new { @class = "form-control", @placeholder = "Password", @type = "Password" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.userLevel)
            @Html.TextBoxFor(m => m.userLevel, new { @class = "form-control", @placeholder = "Access Level" })
        </div>
        <input type="submit" value="Add User" class="btn btn-primary" />

        <h3><small style="color:red;">@ViewBag.ValidateMsg</small></h3>

    }
</div>